default:
  gnn: 'GCN'
  seed: [0, 1, 2, 3, 4]
  epochs: 300
  valid_epoch: 10
  lr: 1e-4
  weight_decay: 5e-4
  layer_num: 2
  hidden_dim: 128
  dropout: 0.5
  patience: 20
  batch_size: 256
  num_heads: 4 # only available for GATConv
  aggr: 'mean' # ['mean', 'max', 'lstm'], only available for SAGEConv

  lm: 'LLaMA' # ['RoBERTa', 'LLaMA']
  cache: '/data/root/LLM4GCL-main/LLM4GCL/embeddings/hidden_embs/'
  cache_batch_size: 30
  max_length: 512
search_space:
  gnn: ['GCN']
  lr: [1e-5, 1e-4, 1e-3]
  hidden_dim: [128, 256]

