default:
  lm: 'LLaMA'
  seed: [0, 1, 2, 3, 4]
  epochs: 10
  valid_epoch: 1
  warmup_epochs: 1
  lr: 2e-4
  min_lr: 5e-6
  grad_steps: 2
  weight_decay: 5e-2
  dropout: 0.1
  att_dropout: 0.1
  patience: 5
  batch_size: 5
  max_length: 512
  LoRA:
    use_lora: true
    lora_r: 5
    lora_alpha: 16
    lora_dropout: 0.05

  T: 1.0
  sample_num: 50
  hop: [20, 20]
  mode: 'neighbors' # ['neighbors', 'ego', 'pure']
  include_label: false
  max_node_text_len: 128

search_space:
  lr: [1e-4, 2e-4, 5e-4]